import PropTypes from 'prop-types';

const Transaction = function ({ transactionItems }) {
  return (
    <table className="transaction-history">
      <thead>
        <tr>
          <th>Type</th>
          <th>Amount</th>
          <th>Currency</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>{transactionItems[0].type}</td>
          <td>{transactionItems[0].amount}</td>
          <td>{transactionItems[0].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[1].type}</td>
          <td>{transactionItems[1].amount}</td>
          <td>{transactionItems[1].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[2].type}</td>
          <td>{transactionItems[2].amount}</td>
          <td>{transactionItems[2].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[3].type}</td>
          <td>{transactionItems[3].amount}</td>
          <td>{transactionItems[3].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[4].type}</td>
          <td>{transactionItems[4].amount}</td>
          <td>{transactionItems[4].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[5].type}</td>
          <td>{transactionItems[5].amount}</td>
          <td>{transactionItems[5].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[6].type}</td>
          <td>{transactionItems[6].amount}</td>
          <td>{transactionItems[6].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[7].type}</td>
          <td>{transactionItems[7].amount}</td>
          <td>{transactionItems[7].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[8].type}</td>
          <td>{transactionItems[8].amount}</td>
          <td>{transactionItems[8].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[9].type}</td>
          <td>{transactionItems[9].amount}</td>
          <td>{transactionItems[9].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[10].type}</td>
          <td>{transactionItems[10].amount}</td>
          <td>{transactionItems[10].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[11].type}</td>
          <td>{transactionItems[11].amount}</td>
          <td>{transactionItems[11].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[12].type}</td>
          <td>{transactionItems[12].amount}</td>
          <td>{transactionItems[12].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[13].type}</td>
          <td>{transactionItems[13].amount}</td>
          <td>{transactionItems[13].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[14].type}</td>
          <td>{transactionItems[14].amount}</td>
          <td>{transactionItems[14].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[15].type}</td>
          <td>{transactionItems[15].amount}</td>
          <td>{transactionItems[15].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[16].type}</td>
          <td>{transactionItems[16].amount}</td>
          <td>{transactionItems[16].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[17].type}</td>
          <td>{transactionItems[17].amount}</td>
          <td>{transactionItems[17].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[18].type}</td>
          <td>{transactionItems[18].amount}</td>
          <td>{transactionItems[18].currency}</td>
        </tr>
        <tr>
          <td>{transactionItems[19].type}</td>
          <td>{transactionItems[19].amount}</td>
          <td>{transactionItems[19].currency}</td>
        </tr>
      </tbody>
    </table>
  );
};

export default Transaction;
